/** ISO 3166 codes for flagcdn.com — includes gb-eng / gb-sct for home nations */
const TEAM_FLAG_CODES: Record<string, string> = {
  'Mexico': 'mx',
  'South Africa': 'za',
  'South Korea': 'kr',
  'Czech Republic': 'cz',
  'Canada': 'ca',
  'Bosnia & Herzegovina': 'ba',
  'USA': 'us',
  'Paraguay': 'py',
  'Qatar': 'qa',
  'Switzerland': 'ch',
  'Brazil': 'br',
  'Morocco': 'ma',
  'Haiti': 'ht',
  'Scotland': 'gb-sct',
  'Australia': 'au',
  'Turkey': 'tr',
  'Germany': 'de',
  'Curaçao': 'cw',
  'Netherlands': 'nl',
  'Japan': 'jp',
  'Ivory Coast': 'ci',
  'Ecuador': 'ec',
  'Sweden': 'se',
  'Tunisia': 'tn',
  'Spain': 'es',
  'Cape Verde': 'cv',
  'Belgium': 'be',
  'Egypt': 'eg',
  'Saudi Arabia': 'sa',
  'Uruguay': 'uy',
  'Iran': 'ir',
  'New Zealand': 'nz',
  'France': 'fr',
  'Senegal': 'sn',
  'Iraq': 'iq',
  'Norway': 'no',
  'Argentina': 'ar',
  'Algeria': 'dz',
  'Austria': 'at',
  'Jordan': 'jo',
  'Portugal': 'pt',
  'DR Congo': 'cd',
  'England': 'gb-eng',
  'Croatia': 'hr',
  'Ghana': 'gh',
  'Panama': 'pa',
  'Uzbekistan': 'uz',
  'Colombia': 'co',
  // API-Football name variants (mirrors api/lib/syncResults.ts)
  'United States': 'us',
  'Bosnia and Herzegovina': 'ba',
  'Korea Republic': 'kr',
  'Czechia': 'cz',
  "Cote d'Ivoire": 'ci',
  "Côte d'Ivoire": 'ci',
  'Congo DR': 'cd',
  'Democratic Republic of the Congo': 'cd',
  'Cape-Verde': 'cv',
  'IR Iran': 'ir',
  'China': 'cn',
  'China PR': 'cn',
  'Curacao': 'cw',
  'New-Zealand': 'nz',
}

export function getTeamFlagCode(teamName: string): string | null {
  return TEAM_FLAG_CODES[teamName] ?? null
}

export function getFlagImageUrl(code: string, width = 40): string {
  const w = Math.max(20, Math.min(width, 80))
  const h = Math.round(w * 0.75)
  return `https://flagcdn.com/${w}x${h}/${code}.png`
}

/** Short codes for narrow match cards on mobile */
const TEAM_ABBREVIATIONS: Record<string, string> = {
  'Mexico': 'MEX',
  'South Africa': 'RSA',
  'South Korea': 'KOR',
  'Czech Republic': 'CZE',
  'Canada': 'CAN',
  'Bosnia & Herzegovina': 'BIH',
  'USA': 'USA',
  'Paraguay': 'PAR',
  'Qatar': 'QAT',
  'Switzerland': 'SUI',
  'Brazil': 'BRA',
  'Morocco': 'MAR',
  'Haiti': 'HAI',
  'Scotland': 'SCO',
  'Australia': 'AUS',
  'Turkey': 'TUR',
  'Germany': 'GER',
  'Curaçao': 'CUW',
  'Netherlands': 'NED',
  'Japan': 'JPN',
  'Ivory Coast': 'CIV',
  'Ecuador': 'ECU',
  'Sweden': 'SWE',
  'Tunisia': 'TUN',
  'Spain': 'ESP',
  'Cape Verde': 'CPV',
  'Belgium': 'BEL',
  'Egypt': 'EGY',
  'Saudi Arabia': 'KSA',
  'Uruguay': 'URU',
  'Iran': 'IRN',
  'New Zealand': 'NZL',
  'France': 'FRA',
  'Senegal': 'SEN',
  'Iraq': 'IRQ',
  'Norway': 'NOR',
  'Argentina': 'ARG',
  'Algeria': 'ALG',
  'Austria': 'AUT',
  'Jordan': 'JOR',
  'Portugal': 'POR',
  'DR Congo': 'COD',
  'England': 'ENG',
  'Croatia': 'CRO',
  'Ghana': 'GHA',
  'Panama': 'PAN',
  'Uzbekistan': 'UZB',
  'Colombia': 'COL',
  // API-Football name variants
  'United States': 'USA',
  'Bosnia and Herzegovina': 'BIH',
  'Korea Republic': 'KOR',
  'Czechia': 'CZE',
  "Cote d'Ivoire": 'CIV',
  "Côte d'Ivoire": 'CIV',
  'Congo DR': 'COD',
  'Democratic Republic of the Congo': 'COD',
  'Cape-Verde': 'CPV',
  'IR Iran': 'IRN',
  'China': 'CHN',
  'China PR': 'CHN',
  'Curacao': 'CUW',
  'New-Zealand': 'NZL',
}

export function getTeamAbbreviation(teamName: string): string {
  return TEAM_ABBREVIATIONS[teamName] ?? teamName.slice(0, 3).toUpperCase()
}

export function isPlaceholderTeam(teamName: string): boolean {
  return !getTeamFlagCode(teamName)
}
